name = "apichai-crm"
account_id = "18635b320bce16ac4ea741ba1f742647"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Production Database (default - ใช้เมื่อ deploy)
[[d1_databases]]
binding = "DB"
database_name = "apichai-crm-prod"
database_id = "2e4f9fcd-9c3a-49c2-9fa9-8808ea80ca84"

# Development Environment (ใช้เมื่อ run local dev)
[env.dev]

[env.dev.vars]
JWT_SECRET = "dev-secret-key-apichai-crm-2024"

[[env.dev.d1_databases]]
binding = "DB"
database_name = "apichai-crm-local"
database_id = "2e4f9fcd-9c3a-49c2-9fa9-8808ea80ca84" # ใช้ตัวเดียวกับ prod เนื่องจากติด limit account

# QA Environment (ใช้สำหรับทดสอบแยกจาก production)
[env.qa]

[[env.qa.d1_databases]]
binding = "DB"
database_name = "apichai-crm-qa"
database_id = "local-qa-database-id"
